<a href="https://colab.research.google.com/github/KolipakaRamesh/AIML_Practice_Excercises/blob/main/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.identity(3)

# Print the identity matrix
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np

# Create a diagonal matrix from a list of values
diagonal_values = [1, 2, 3, 4]
diagonal_matrix = np.diag(diagonal_values)

# Print the diagonal matrix
print(diagonal_matrix)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
import numpy as np

# Define two vectors
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Calculate the dot product
dot_product = np.dot(vector1, vector2)

# Print the dot product
print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Dot product:", dot_product)

Vector 1: [1 2 3]
Vector 2: [4 5 6]
Dot product: 32


In [1]:
import numpy as np

# Define two vectors
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Calculate the cross product
cross_product = np.cross(vector1, vector2)

# Calculate the magnitude of the cross product
magnitude_cross_product = np.linalg.norm(cross_product)


# Print the vector and cross product
print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Cross product:", cross_product)
print("Magnitude of cross product:", magnitude_cross_product)

Vector 1: [1 2 3]
Vector 2: [4 5 6]
Cross product: [-3  6 -3]
Magnitude of cross product: 7.3484692283495345


In [ ]:
import numpy as np

# Create a sample matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Calculate the transpose of the matrix
transpose_matrix = np.transpose(matrix)

# Print the original and transpose matrices
print("Original Matrix:\n", matrix)
print("\nTranspose Matrix:\n", transpose_matrix)

Original Matrix:
 [[1 2 3]
 [4 5 6]]

Transpose Matrix:
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
import numpy as np
from numpy.linalg import inv

# Create a square matrix
matrix = np.array([[1, 2],
                   [3, 4]])

# Calculate the inverse of the matrix
try:
    inverse_matrix = inv(matrix)
    # Print the original and inverse matrices
    print("Original Matrix:\n", matrix)
    print("\nInverse Matrix:\n", inverse_matrix)
except np.linalg.LinAlgError:
    print("The matrix is singular and does not have an inverse.")

Original Matrix:
 [[1 2]
 [3 4]]

Inverse Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
import numpy as np

# Create a sample square matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the trace of the matrix
trace_value = np.trace(matrix)

# Print the original matrix and its trace
print("Original Matrix:\n", matrix)
print("\nTrace of the matrix:", trace_value)

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Trace of the matrix: 15


In [ ]:
import numpy as np
from numpy.linalg import det

# Create a sample square matrix
matrix = np.array([[1, 2],
                   [3, 4]])

# Calculate the determinant of the matrix
determinant_value = det(matrix)

# Print the original matrix and its determinant
print("Original Matrix:\n", matrix)
print("\nDeterminant of the matrix:", determinant_value)

Original Matrix:
 [[1 2]
 [3 4]]

Determinant of the matrix: -2.0000000000000004


In [ ]:
import numpy as np
from numpy.linalg import eigh

# Create a symmetric matrix
# A matrix A is symmetric if A = A^T
matrix = np.array([[2, 1],
                   [1, 3]])

# Perform eigendecomposition for a symmetric matrix
# eigh returns eigenvalues and eigenvectors for symmetric matrices
eigenvalues, eigenvectors = eigh(matrix)

# Print the original matrix, eigenvalues, and eigenvectors
print("Original Symmetric Matrix:\n", matrix)
print("\nEigenvalues:", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

# Verify the decomposition: A = V @ D @ V.T
# V is the matrix of eigenvectors (eigenvectors), D is a diagonal matrix of eigenvalues
D = np.diag(eigenvalues)
reconstructed_matrix = eigenvectors @ D @ eigenvectors.T

print("\nReconstructed Matrix (V @ D @ V.T):\n", reconstructed_matrix)

Original Symmetric Matrix:
 [[2 1]
 [1 3]]

Eigenvalues: [1.38196601 3.61803399]

Eigenvectors:
 [[-0.85065081  0.52573111]
 [ 0.52573111  0.85065081]]

Reconstructed Matrix (V @ D @ V.T):
 [[2. 1.]
 [1. 3.]]


In [ ]:
import numpy as np
from numpy.linalg import eig

# Create a sample non-symmetric matrix
matrix = np.array([[3, 2],
                   [1, 4]])

# Perform eigendecomposition for a general matrix
# eig returns eigenvalues and eigenvectors
eigenvalues, eigenvectors = eig(matrix)

# Print the original matrix, eigenvalues, and eigenvectors
print("Original Non-Symmetric Matrix:\n", matrix)
print("\nEigenvalues:", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

# Verify the decomposition: A @ v = lambda * v
# Where A is the matrix, v is an eigenvector, and lambda is an eigenvalue
# We can check this for the first eigenvector and eigenvalue
v1 = eigenvectors[:, 0]
lambda1 = eigenvalues[0]

print("\nVerification (A @ v1):", matrix @ v1)
print("Verification (lambda1 * v1):", lambda1 * v1)

# We can check this for the second eigenvector and eigenvalue
v2 = eigenvectors[:, 1]
lambda2 = eigenvalues[1]

print("\nVerification (A @ v2):", matrix @ v2)
print("Verification (lambda2 * v2):", lambda2 * v2)

Original Non-Symmetric Matrix:
 [[3 2]
 [1 4]]

Eigenvalues: [2. 5.]

Eigenvectors:
 [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]

Verification (A @ v1): [-1.78885438  0.89442719]
Verification (lambda1 * v1): [-1.78885438  0.89442719]

Verification (A @ v2): [-3.53553391 -3.53553391]
Verification (lambda2 * v2): [-3.53553391 -3.53553391]
