<a href="https://colab.research.google.com/github/KolipakaRamesh/AIML_Practice_Excercises/blob/main/SymmetricDecomposition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create a 3x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Transpose the matrix
A_transpose = A.T

# Add the original and transposed matrices
sum_matrix = A + A_transpose

# Divide the result by 2
result_matrix = sum_matrix / 2

# Display the result
print("Original Matrix A:")
display(A)
print("\nTransposed Matrix A_transpose:")
display(A_transpose)
print("\nSum of A and A_transpose:")
display(sum_matrix)
print("\nResult (Sum divided by 2):")
display(result_matrix)

Original Matrix A:


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


Transposed Matrix A_transpose:


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])


Sum of A and A_transpose:


array([[ 2,  6, 10],
       [ 6, 10, 14],
       [10, 14, 18]])


Result (Sum divided by 2):


array([[1., 3., 5.],
       [3., 5., 7.],
       [5., 7., 9.]])

Now, I'll perform the subtraction of the transposed matrix from the original and divide the result by 2.

In [3]:
import numpy as np

# Create a 3x3 matrix (using the same matrix A as before)
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Transpose the matrix
A_transpose = A.T

# Subtract the transposed matrix from the original
difference_matrix = A - A_transpose

# Divide the result by 2
result_matrix_subtraction = difference_matrix / 2

# Display the result
print("Original Matrix A:")
display(A)
print("\nTransposed Matrix A_transpose:")
display(A_transpose)
print("\nDifference of A and A_transpose:")
display(difference_matrix)
print("\nResult (Difference divided by 2):")
display(result_matrix_subtraction)

Original Matrix A:


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


Transposed Matrix A_transpose:


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])


Difference of A and A_transpose:


array([[ 0, -2, -4],
       [ 2,  0, -2],
       [ 4,  2,  0]])


Result (Difference divided by 2):


array([[ 0., -1., -2.],
       [ 1.,  0., -1.],
       [ 2.,  1.,  0.]])

In [4]:
# Sum the two result matrices
sum_of_results = result_matrix + result_matrix_subtraction

# Display the sum
print("Sum of result_matrix and result_matrix_subtraction:")
display(sum_of_results)

Sum of result_matrix and result_matrix_subtraction:


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])